// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type NpaPolicyRuleDataAccessMethod string

const (
	NpaPolicyRuleDataAccessMethodClient     NpaPolicyRuleDataAccessMethod = "Client"
	NpaPolicyRuleDataAccessMethodClientless NpaPolicyRuleDataAccessMethod = "Clientless"
)

func (e NpaPolicyRuleDataAccessMethod) ToPointer() *NpaPolicyRuleDataAccessMethod {
	return &e
}

func (e *NpaPolicyRuleDataAccessMethod) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Client":
		fallthrough
	case "Clientless":
		*e = NpaPolicyRuleDataAccessMethod(v)
		return nil
	default:
		return fmt.Errorf("invalid value for NpaPolicyRuleDataAccessMethod: %v", v)
	}
}

type NpaPolicyRuleDataMatchCriteriaActionActionName string

const (
	NpaPolicyRuleDataMatchCriteriaActionActionNameAllow NpaPolicyRuleDataMatchCriteriaActionActionName = "allow"
	NpaPolicyRuleDataMatchCriteriaActionActionNameBlock NpaPolicyRuleDataMatchCriteriaActionActionName = "block"
)

func (e NpaPolicyRuleDataMatchCriteriaActionActionName) ToPointer() *NpaPolicyRuleDataMatchCriteriaActionActionName {
	return &e
}

func (e *NpaPolicyRuleDataMatchCriteriaActionActionName) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "allow":
		fallthrough
	case "block":
		*e = NpaPolicyRuleDataMatchCriteriaActionActionName(v)
		return nil
	default:
		return fmt.Errorf("invalid value for NpaPolicyRuleDataMatchCriteriaActionActionName: %v", v)
	}
}

type NpaPolicyRuleDataMatchCriteriaAction struct {
	ActionName *NpaPolicyRuleDataMatchCriteriaActionActionName `json:"action_name,omitempty"`
}

func (o *NpaPolicyRuleDataMatchCriteriaAction) GetActionName() *NpaPolicyRuleDataMatchCriteriaActionActionName {
	if o == nil {
		return nil
	}
	return o.ActionName
}

type NpaPolicyRuleDataPolicyType string

const (
	NpaPolicyRuleDataPolicyTypePrivateApp NpaPolicyRuleDataPolicyType = "private-app"
)

func (e NpaPolicyRuleDataPolicyType) ToPointer() *NpaPolicyRuleDataPolicyType {
	return &e
}

func (e *NpaPolicyRuleDataPolicyType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "private-app":
		*e = NpaPolicyRuleDataPolicyType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for NpaPolicyRuleDataPolicyType: %v", v)
	}
}

type NpaPolicyRuleDataPrivateAppsWithActivitiesActivitiesActivity string

const (
	NpaPolicyRuleDataPrivateAppsWithActivitiesActivitiesActivityAny NpaPolicyRuleDataPrivateAppsWithActivitiesActivitiesActivity = "any"
)

func (e NpaPolicyRuleDataPrivateAppsWithActivitiesActivitiesActivity) ToPointer() *NpaPolicyRuleDataPrivateAppsWithActivitiesActivitiesActivity {
	return &e
}

func (e *NpaPolicyRuleDataPrivateAppsWithActivitiesActivitiesActivity) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "any":
		*e = NpaPolicyRuleDataPrivateAppsWithActivitiesActivitiesActivity(v)
		return nil
	default:
		return fmt.Errorf("invalid value for NpaPolicyRuleDataPrivateAppsWithActivitiesActivitiesActivity: %v", v)
	}
}

type NpaPolicyRuleDataPrivateAppsWithActivitiesActivities struct {
	Activity          *NpaPolicyRuleDataPrivateAppsWithActivitiesActivitiesActivity `json:"activity,omitempty"`
	ListOfConstraints []string                                                      `json:"list_of_constraints,omitempty"`
}

func (o *NpaPolicyRuleDataPrivateAppsWithActivitiesActivities) GetActivity() *NpaPolicyRuleDataPrivateAppsWithActivitiesActivitiesActivity {
	if o == nil {
		return nil
	}
	return o.Activity
}

func (o *NpaPolicyRuleDataPrivateAppsWithActivitiesActivities) GetListOfConstraints() []string {
	if o == nil {
		return nil
	}
	return o.ListOfConstraints
}

type NpaPolicyRuleDataPrivateAppsWithActivities struct {
	Activities []NpaPolicyRuleDataPrivateAppsWithActivitiesActivities `json:"activities,omitempty"`
	AppName    *string                                                `json:"appName,omitempty"`
}

func (o *NpaPolicyRuleDataPrivateAppsWithActivities) GetActivities() []NpaPolicyRuleDataPrivateAppsWithActivitiesActivities {
	if o == nil {
		return nil
	}
	return o.Activities
}

func (o *NpaPolicyRuleDataPrivateAppsWithActivities) GetAppName() *string {
	if o == nil {
		return nil
	}
	return o.AppName
}

type NpaPolicyRuleDataUserType string

const (
	NpaPolicyRuleDataUserTypeUser NpaPolicyRuleDataUserType = "user"
)

func (e NpaPolicyRuleDataUserType) ToPointer() *NpaPolicyRuleDataUserType {
	return &e
}

func (e *NpaPolicyRuleDataUserType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "user":
		*e = NpaPolicyRuleDataUserType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for NpaPolicyRuleDataUserType: %v", v)
	}
}

type NpaPolicyRuleData struct {
	AccessMethod              *NpaPolicyRuleDataAccessMethod               `json:"access_method,omitempty"`
	BNegateNetLocation        *bool                                        `json:"b_negateNetLocation,omitempty"`
	BNegateSrcCountries       *bool                                        `json:"b_negateSrcCountries,omitempty"`
	Classification            *string                                      `json:"classification,omitempty"`
	DlpActions                []NpaPolicyRuleDlp                           `json:"dlp_actions,omitempty"`
	ExternalDlp               *bool                                        `json:"external_dlp,omitempty"`
	JSONVersion               *int64                                       `json:"json_version,omitempty"`
	MatchCriteriaAction       *NpaPolicyRuleDataMatchCriteriaAction        `json:"match_criteria_action,omitempty"`
	NetLocationObj            []string                                     `json:"net_location_obj,omitempty"`
	OrganizationUnits         []string                                     `json:"organization_units,omitempty"`
	PolicyType                *NpaPolicyRuleDataPolicyType                 `json:"policy_type,omitempty"`
	PrivateAppIds             []string                                     `json:"privateAppIds,omitempty"`
	PrivateAppTagIds          []string                                     `json:"privateAppTagIds,omitempty"`
	PrivateAppTags            []string                                     `json:"privateAppTags,omitempty"`
	PrivateApps               []string                                     `json:"privateApps,omitempty"`
	PrivateAppsWithActivities []NpaPolicyRuleDataPrivateAppsWithActivities `json:"privateAppsWithActivities,omitempty"`
	ShowDlpProfileActionTable *bool                                        `json:"show_dlp_profile_action_table,omitempty"`
	SrcCountries              []string                                     `json:"srcCountries,omitempty"`
	UserGroups                []string                                     `json:"userGroups,omitempty"`
	UserType                  *NpaPolicyRuleDataUserType                   `json:"userType,omitempty"`
	Users                     []string                                     `json:"users,omitempty"`
	Version                   *int64                                       `json:"version,omitempty"`
}

func (o *NpaPolicyRuleData) GetAccessMethod() *NpaPolicyRuleDataAccessMethod {
	if o == nil {
		return nil
	}
	return o.AccessMethod
}

func (o *NpaPolicyRuleData) GetBNegateNetLocation() *bool {
	if o == nil {
		return nil
	}
	return o.BNegateNetLocation
}

func (o *NpaPolicyRuleData) GetBNegateSrcCountries() *bool {
	if o == nil {
		return nil
	}
	return o.BNegateSrcCountries
}

func (o *NpaPolicyRuleData) GetClassification() *string {
	if o == nil {
		return nil
	}
	return o.Classification
}

func (o *NpaPolicyRuleData) GetDlpActions() []NpaPolicyRuleDlp {
	if o == nil {
		return nil
	}
	return o.DlpActions
}

func (o *NpaPolicyRuleData) GetExternalDlp() *bool {
	if o == nil {
		return nil
	}
	return o.ExternalDlp
}

func (o *NpaPolicyRuleData) GetJSONVersion() *int64 {
	if o == nil {
		return nil
	}
	return o.JSONVersion
}

func (o *NpaPolicyRuleData) GetMatchCriteriaAction() *NpaPolicyRuleDataMatchCriteriaAction {
	if o == nil {
		return nil
	}
	return o.MatchCriteriaAction
}

func (o *NpaPolicyRuleData) GetNetLocationObj() []string {
	if o == nil {
		return nil
	}
	return o.NetLocationObj
}

func (o *NpaPolicyRuleData) GetOrganizationUnits() []string {
	if o == nil {
		return nil
	}
	return o.OrganizationUnits
}

func (o *NpaPolicyRuleData) GetPolicyType() *NpaPolicyRuleDataPolicyType {
	if o == nil {
		return nil
	}
	return o.PolicyType
}

func (o *NpaPolicyRuleData) GetPrivateAppIds() []string {
	if o == nil {
		return nil
	}
	return o.PrivateAppIds
}

func (o *NpaPolicyRuleData) GetPrivateAppTagIds() []string {
	if o == nil {
		return nil
	}
	return o.PrivateAppTagIds
}

func (o *NpaPolicyRuleData) GetPrivateAppTags() []string {
	if o == nil {
		return nil
	}
	return o.PrivateAppTags
}

func (o *NpaPolicyRuleData) GetPrivateApps() []string {
	if o == nil {
		return nil
	}
	return o.PrivateApps
}

func (o *NpaPolicyRuleData) GetPrivateAppsWithActivities() []NpaPolicyRuleDataPrivateAppsWithActivities {
	if o == nil {
		return nil
	}
	return o.PrivateAppsWithActivities
}

func (o *NpaPolicyRuleData) GetShowDlpProfileActionTable() *bool {
	if o == nil {
		return nil
	}
	return o.ShowDlpProfileActionTable
}

func (o *NpaPolicyRuleData) GetSrcCountries() []string {
	if o == nil {
		return nil
	}
	return o.SrcCountries
}

func (o *NpaPolicyRuleData) GetUserGroups() []string {
	if o == nil {
		return nil
	}
	return o.UserGroups
}

func (o *NpaPolicyRuleData) GetUserType() *NpaPolicyRuleDataUserType {
	if o == nil {
		return nil
	}
	return o.UserType
}

func (o *NpaPolicyRuleData) GetUsers() []string {
	if o == nil {
		return nil
	}
	return o.Users
}

func (o *NpaPolicyRuleData) GetVersion() *int64 {
	if o == nil {
		return nil
	}
	return o.Version
}
