// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type NpaPolicyResponse400 struct {
	Result *string `json:"result,omitempty"`
	Status *int64  `json:"status,omitempty"`
}
