// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type NpaPolicyResponseItem struct {
	GroupID  *int64             `json:"group_id,omitempty"`
	RuleData *NpaPolicyRuleData `json:"rule_data,omitempty"`
	RuleID   *int64             `json:"rule_id,omitempty"`
	RuleName *string            `json:"rule_name,omitempty"`
}
