// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type CreateANpaPolicyGroupRequestBody struct {
	GroupName     *string `json:"group_name,omitempty"`
	GroupPinnedID *string `json:"group_pinned_id,omitempty"`
	GroupProdID   *string `json:"group_prod_id,omitempty"`
	GroupType     *string `json:"group_type,omitempty"`
	ModifyBy      *string `json:"modify_by,omitempty"`
	ModifyType    *string `json:"modify_type,omitempty"`
}

type CreateANpaPolicyGroupRequest struct {
	RequestBody *CreateANpaPolicyGroupRequestBody `request:"mediaType=application/json"`
	// flag to skip output except status code
	Silent *string `queryParam:"style=form,explode=true,name=silent"`
}

// CreateANpaPolicyGroup400ApplicationJSON - Invalid request
type CreateANpaPolicyGroup400ApplicationJSON struct {
	Result *string `json:"result,omitempty"`
	Status *string `json:"status,omitempty"`
}

// CreateANpaPolicyGroup200ApplicationJSON - successful operation
type CreateANpaPolicyGroup200ApplicationJSON struct {
	CanBeEditedDeleted *string `json:"can_be_edited_deleted,omitempty"`
	GroupID            *string `json:"group_id,omitempty"`
	GroupName          *string `json:"group_name,omitempty"`
	GroupPinnedID      *string `json:"group_pinned_id,omitempty"`
	GroupProdID        *string `json:"group_prod_id,omitempty"`
	GroupType          *string `json:"group_type,omitempty"`
	ModifyTime         *string `json:"modify_time,omitempty"`
	ModifyType         *string `json:"modify_type,omitempty"`
}

type CreateANpaPolicyGroupResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// successful operation
	CreateANpaPolicyGroup200ApplicationJSONObject *CreateANpaPolicyGroup200ApplicationJSON
	// Invalid request
	CreateANpaPolicyGroup400ApplicationJSONObject *CreateANpaPolicyGroup400ApplicationJSON
}
