// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type CreateANpaPolicyRequestBodyRuleDataMatchCriteriaAction struct {
	ActionName *string `json:"action_name,omitempty"`
}

type CreateANpaPolicyRequestBodyRuleDataPrivateAppsWithActivitiesActivities struct {
	Activity          *string  `json:"activity,omitempty"`
	ListOfConstraints []string `json:"list_of_constraints,omitempty"`
}

type CreateANpaPolicyRequestBodyRuleDataPrivateAppsWithActivities struct {
	Activities []CreateANpaPolicyRequestBodyRuleDataPrivateAppsWithActivitiesActivities `json:"activities,omitempty"`
	AppName    *string                                                                  `json:"appName,omitempty"`
}

type CreateANpaPolicyRequestBodyRuleData struct {
	AccessMethod              *string                                                        `json:"access_method,omitempty"`
	BNegateNetLocation        *string                                                        `json:"b_negateNetLocation,omitempty"`
	BNegateSrcCountries       *string                                                        `json:"b_negateSrcCountries,omitempty"`
	Classification            *string                                                        `json:"classification,omitempty"`
	ExcludedUsers             []string                                                       `json:"excludedUsers,omitempty"`
	ExternalDlp               *string                                                        `json:"external_dlp,omitempty"`
	JSONVersion               *string                                                        `json:"json_version,omitempty"`
	MatchCriteriaAction       *CreateANpaPolicyRequestBodyRuleDataMatchCriteriaAction        `json:"match_criteria_action,omitempty"`
	NetLocationObj            []string                                                       `json:"net_location_obj,omitempty"`
	PolicyType                *string                                                        `json:"policy_type,omitempty"`
	PrivateAppIds             []string                                                       `json:"privateAppIds,omitempty"`
	PrivateAppTagIds          []string                                                       `json:"privateAppTagIds,omitempty"`
	PrivateAppTags            []string                                                       `json:"privateAppTags,omitempty"`
	PrivateApps               []string                                                       `json:"privateApps,omitempty"`
	PrivateAppsWithActivities []CreateANpaPolicyRequestBodyRuleDataPrivateAppsWithActivities `json:"privateAppsWithActivities,omitempty"`
	ShowDlpProfileActionTable *string                                                        `json:"show_dlp_profile_action_table,omitempty"`
	SrcCountries              []string                                                       `json:"srcCountries,omitempty"`
	UserType                  *string                                                        `json:"userType,omitempty"`
	Users                     []string                                                       `json:"users,omitempty"`
	Version                   *string                                                        `json:"version,omitempty"`
}

type CreateANpaPolicyRequestBodyRuleOrder struct {
	Order    *string `json:"order,omitempty"`
	Position *string `json:"position,omitempty"`
}

type CreateANpaPolicyRequestBody struct {
	Description *string                               `json:"description,omitempty"`
	GroupID     *string                               `json:"group_id,omitempty"`
	RuleData    *CreateANpaPolicyRequestBodyRuleData  `json:"rule_data,omitempty"`
	RuleName    *string                               `json:"rule_name,omitempty"`
	RuleOrder   *CreateANpaPolicyRequestBodyRuleOrder `json:"rule_order,omitempty"`
}

type CreateANpaPolicyRequest struct {
	RequestBody *CreateANpaPolicyRequestBody `request:"mediaType=application/json"`
	// flag to skip output except status code
	Silent *string `queryParam:"style=form,explode=true,name=silent"`
}

// CreateANpaPolicy400ApplicationJSON - Invalid request
type CreateANpaPolicy400ApplicationJSON struct {
	Result *string `json:"result,omitempty"`
	Status *string `json:"status,omitempty"`
}

type CreateANpaPolicy200ApplicationJSONRuleDataMatchCriteriaAction struct {
	ActionName *string `json:"action_name,omitempty"`
}

type CreateANpaPolicy200ApplicationJSONRuleDataPrivateAppsWithActivitiesActivities struct {
	Activity          *string  `json:"activity,omitempty"`
	ListOfConstraints []string `json:"list_of_constraints,omitempty"`
}

type CreateANpaPolicy200ApplicationJSONRuleDataPrivateAppsWithActivities struct {
	Activities []CreateANpaPolicy200ApplicationJSONRuleDataPrivateAppsWithActivitiesActivities `json:"activities,omitempty"`
	AppName    *string                                                                         `json:"appName,omitempty"`
}

type CreateANpaPolicy200ApplicationJSONRuleData struct {
	AccessMethod              *string                                                               `json:"access_method,omitempty"`
	BNegateNetLocation        *string                                                               `json:"b_negateNetLocation,omitempty"`
	BNegateSrcCountries       *string                                                               `json:"b_negateSrcCountries,omitempty"`
	Classification            *string                                                               `json:"classification,omitempty"`
	ExcludedUsers             []string                                                              `json:"excludedUsers,omitempty"`
	ExternalDlp               *string                                                               `json:"external_dlp,omitempty"`
	JSONVersion               *string                                                               `json:"json_version,omitempty"`
	MatchCriteriaAction       *CreateANpaPolicy200ApplicationJSONRuleDataMatchCriteriaAction        `json:"match_criteria_action,omitempty"`
	NetLocationObj            []string                                                              `json:"net_location_obj,omitempty"`
	PolicyType                *string                                                               `json:"policy_type,omitempty"`
	PrivateAppIds             []string                                                              `json:"privateAppIds,omitempty"`
	PrivateAppTagIds          []string                                                              `json:"privateAppTagIds,omitempty"`
	PrivateAppTags            []string                                                              `json:"privateAppTags,omitempty"`
	PrivateApps               []string                                                              `json:"privateApps,omitempty"`
	PrivateAppsWithActivities []CreateANpaPolicy200ApplicationJSONRuleDataPrivateAppsWithActivities `json:"privateAppsWithActivities,omitempty"`
	ShowDlpProfileActionTable *string                                                               `json:"show_dlp_profile_action_table,omitempty"`
	SrcCountries              []string                                                              `json:"srcCountries,omitempty"`
	UserType                  *string                                                               `json:"userType,omitempty"`
	Users                     []string                                                              `json:"users,omitempty"`
	Version                   *string                                                               `json:"version,omitempty"`
}

// CreateANpaPolicy200ApplicationJSON - successful operation
type CreateANpaPolicy200ApplicationJSON struct {
	GroupID  *string                                     `json:"group_id,omitempty"`
	RuleData *CreateANpaPolicy200ApplicationJSONRuleData `json:"rule_data,omitempty"`
	RuleID   *string                                     `json:"rule_id,omitempty"`
	RuleName *string                                     `json:"rule_name,omitempty"`
}

type CreateANpaPolicyResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// successful operation
	CreateANpaPolicy200ApplicationJSONObject *CreateANpaPolicy200ApplicationJSON
	// Invalid request
	CreateANpaPolicy400ApplicationJSONObject *CreateANpaPolicy400ApplicationJSON
}
