// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Platform/internal/sdk/pkg/models/shared"
	"encoding/json"
	"fmt"
	"net/http"
)

type DeleteNpaRulesIDRequest struct {
	// npa policy id
	ID int `pathParam:"style=simple,explode=false,name=id"`
}

type DeleteNpaRulesID200ApplicationJSONStatus string

const (
	DeleteNpaRulesID200ApplicationJSONStatusSuccess DeleteNpaRulesID200ApplicationJSONStatus = "success"
	DeleteNpaRulesID200ApplicationJSONStatusError   DeleteNpaRulesID200ApplicationJSONStatus = "error"
)

func (e DeleteNpaRulesID200ApplicationJSONStatus) ToPointer() *DeleteNpaRulesID200ApplicationJSONStatus {
	return &e
}

func (e *DeleteNpaRulesID200ApplicationJSONStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "success":
		fallthrough
	case "error":
		*e = DeleteNpaRulesID200ApplicationJSONStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DeleteNpaRulesID200ApplicationJSONStatus: %v", v)
	}
}

// DeleteNpaRulesID200ApplicationJSON - successful operation
type DeleteNpaRulesID200ApplicationJSON struct {
	Data   *shared.NpaPolicyResponseItem             `json:"data,omitempty"`
	Status *DeleteNpaRulesID200ApplicationJSONStatus `json:"status,omitempty"`
}

type DeleteNpaRulesIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// successful operation
	DeleteNpaRulesID200ApplicationJSONObject *DeleteNpaRulesID200ApplicationJSON
	// Invalid request
	NpaPolicyResponse400 *shared.NpaPolicyResponse400
}
