// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/API-Dev-NS/terraform-provider-Platform/internal/sdk/pkg/models/shared"
	"net/http"
)

type DeleteNpaRulesIDRequest struct {
	// npa policy id
	ID int `pathParam:"style=simple,explode=false,name=id"`
}

func (o *DeleteNpaRulesIDRequest) GetID() int {
	if o == nil {
		return 0
	}
	return o.ID
}

type Status string

const (
	StatusSuccess Status = "success"
	StatusError   Status = "error"
)

func (e Status) ToPointer() *Status {
	return &e
}

func (e *Status) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "success":
		fallthrough
	case "error":
		*e = Status(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Status: %v", v)
	}
}

// DeleteNpaRulesIDResponseBody - successful operation
type DeleteNpaRulesIDResponseBody struct {
	Data   *shared.NpaPolicyResponseItem `json:"data,omitempty"`
	Status *Status                       `json:"status,omitempty"`
}

func (o *DeleteNpaRulesIDResponseBody) GetData() *shared.NpaPolicyResponseItem {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *DeleteNpaRulesIDResponseBody) GetStatus() *Status {
	if o == nil {
		return nil
	}
	return o.Status
}

type DeleteNpaRulesIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Invalid request
	NpaPolicyResponse400 *shared.NpaPolicyResponse400
	// successful operation
	Object *DeleteNpaRulesIDResponseBody
}

func (o *DeleteNpaRulesIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteNpaRulesIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteNpaRulesIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *DeleteNpaRulesIDResponse) GetNpaPolicyResponse400() *shared.NpaPolicyResponse400 {
	if o == nil {
		return nil
	}
	return o.NpaPolicyResponse400
}

func (o *DeleteNpaRulesIDResponse) GetObject() *DeleteNpaRulesIDResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
