// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetListOfNpaPoliciesRequest struct {
	// Return values only from specified fields
	Fields *string `queryParam:"style=form,explode=true,name=fields"`
	// Query string based on query operaters
	Filter *string `queryParam:"style=form,explode=true,name=filter"`
	// Max number of policies to retrieve. Default will be all policies.
	Limit *string `queryParam:"style=form,explode=true,name=limit"`
	// The offset of the first policy in the list to retrieve.
	Offset *string `queryParam:"style=form,explode=true,name=offset"`
	// Sort retrieved policies by specified field. Default is policy id
	Sortby *string `queryParam:"style=form,explode=true,name=sortby"`
	// Sort in either asc or desc order. The default is asc order
	Sortorder *string `queryParam:"style=form,explode=true,name=sortorder"`
}

// GetListOfNpaPolicies400ApplicationJSON - Invalid request
type GetListOfNpaPolicies400ApplicationJSON struct {
	Result *string `json:"result,omitempty"`
	Status *string `json:"status,omitempty"`
}

type GetListOfNpaPolicies200ApplicationJSONRuleDataMatchCriteriaAction struct {
	ActionName *string `json:"action_name,omitempty"`
}

type GetListOfNpaPolicies200ApplicationJSONRuleDataPrivateAppsWithActivitiesActivities struct {
	Activity          *string  `json:"activity,omitempty"`
	ListOfConstraints []string `json:"list_of_constraints,omitempty"`
}

type GetListOfNpaPolicies200ApplicationJSONRuleDataPrivateAppsWithActivities struct {
	Activities []GetListOfNpaPolicies200ApplicationJSONRuleDataPrivateAppsWithActivitiesActivities `json:"activities,omitempty"`
	AppName    *string                                                                             `json:"appName,omitempty"`
}

type GetListOfNpaPolicies200ApplicationJSONRuleData struct {
	AccessMethod              *string                                                                   `json:"access_method,omitempty"`
	BNegateNetLocation        *string                                                                   `json:"b_negateNetLocation,omitempty"`
	BNegateSrcCountries       *string                                                                   `json:"b_negateSrcCountries,omitempty"`
	Classification            *string                                                                   `json:"classification,omitempty"`
	ExcludedUsers             []string                                                                  `json:"excludedUsers,omitempty"`
	ExternalDlp               *string                                                                   `json:"external_dlp,omitempty"`
	JSONVersion               *string                                                                   `json:"json_version,omitempty"`
	MatchCriteriaAction       *GetListOfNpaPolicies200ApplicationJSONRuleDataMatchCriteriaAction        `json:"match_criteria_action,omitempty"`
	NetLocationObj            []string                                                                  `json:"net_location_obj,omitempty"`
	PolicyType                *string                                                                   `json:"policy_type,omitempty"`
	PrivateAppIds             []string                                                                  `json:"privateAppIds,omitempty"`
	PrivateAppTagIds          []string                                                                  `json:"privateAppTagIds,omitempty"`
	PrivateAppTags            []string                                                                  `json:"privateAppTags,omitempty"`
	PrivateApps               []string                                                                  `json:"privateApps,omitempty"`
	PrivateAppsWithActivities []GetListOfNpaPolicies200ApplicationJSONRuleDataPrivateAppsWithActivities `json:"privateAppsWithActivities,omitempty"`
	ShowDlpProfileActionTable *string                                                                   `json:"show_dlp_profile_action_table,omitempty"`
	SrcCountries              []string                                                                  `json:"srcCountries,omitempty"`
	UserType                  *string                                                                   `json:"userType,omitempty"`
	Users                     []string                                                                  `json:"users,omitempty"`
	Version                   *string                                                                   `json:"version,omitempty"`
}

type GetListOfNpaPolicies200ApplicationJSON struct {
	GroupID  *string                                         `json:"group_id,omitempty"`
	RuleData *GetListOfNpaPolicies200ApplicationJSONRuleData `json:"rule_data,omitempty"`
	RuleID   *string                                         `json:"rule_id,omitempty"`
	RuleName *string                                         `json:"rule_name,omitempty"`
}

type GetListOfNpaPoliciesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// successful operation
	GetListOfNpaPolicies200ApplicationJSONObjects []GetListOfNpaPolicies200ApplicationJSON
	// Invalid request
	GetListOfNpaPolicies400ApplicationJSONObject *GetListOfNpaPolicies400ApplicationJSON
}
