// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetListOfNpaPolicyGroupsRequest struct {
	// Return values only from specified fields
	Fields *string `queryParam:"style=form,explode=true,name=fields"`
	// Query string based on query operaters
	Filter *string `queryParam:"style=form,explode=true,name=filter"`
	// Max number of policy groups to retrieve. Default will be all policy groups.
	Limit *string `queryParam:"style=form,explode=true,name=limit"`
	// The offset of the first policy group in the list to retrieve.
	Offset *string `queryParam:"style=form,explode=true,name=offset"`
	// Sort retrieved policy group by specified field. Default is policy group id
	Sortby *string `queryParam:"style=form,explode=true,name=sortby"`
	// Sort in either asc or desc order. The default is asc order
	Sortorder *string `queryParam:"style=form,explode=true,name=sortorder"`
}

// GetListOfNpaPolicyGroups400ApplicationJSON - Invalid request
type GetListOfNpaPolicyGroups400ApplicationJSON struct {
	Result *string `json:"result,omitempty"`
	Status *string `json:"status,omitempty"`
}

type GetListOfNpaPolicyGroups200ApplicationJSON struct {
	CanBeEditedDeleted *string `json:"can_be_edited_deleted,omitempty"`
	GroupID            *string `json:"group_id,omitempty"`
	GroupName          *string `json:"group_name,omitempty"`
	GroupPinnedID      *string `json:"group_pinned_id,omitempty"`
	GroupProdID        *string `json:"group_prod_id,omitempty"`
	GroupType          *string `json:"group_type,omitempty"`
	ModifyTime         *string `json:"modify_time,omitempty"`
	ModifyType         *string `json:"modify_type,omitempty"`
}

type GetListOfNpaPolicyGroupsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// successful operation
	GetListOfNpaPolicyGroups200ApplicationJSONObjects []GetListOfNpaPolicyGroups200ApplicationJSON
	// Invalid request
	GetListOfNpaPolicyGroups400ApplicationJSONObject *GetListOfNpaPolicyGroups400ApplicationJSON
}
