// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Platform/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetNpaRulesRequest struct {
	// Return values only from specified fields
	Fields *string `queryParam:"style=form,explode=true,name=fields"`
	// Query string based on query operaters
	Filter *string `queryParam:"style=form,explode=true,name=filter"`
	// Max number of policies to retrieve. Default will be all policies.
	Limit *int64 `queryParam:"style=form,explode=true,name=limit"`
	// The offset of the first policy in the list to retrieve.
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
	// Sort retrieved policies by specified field. Default is policy id
	Sortby *string `queryParam:"style=form,explode=true,name=sortby"`
	// Sort in either asc or desc order. The default is asc order
	Sortorder *string `queryParam:"style=form,explode=true,name=sortorder"`
}

type GetNpaRulesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// successful operation
	NpaPolicyResponse []shared.NpaPolicyResponseItem
	// Invalid request
	NpaPolicyResponse400 *shared.NpaPolicyResponse400
}
