// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Platform/internal/sdk/pkg/models/shared"
	"encoding/json"
	"fmt"
	"net/http"
)

type GetNpaRulesIDRequest struct {
	// Return values only from specified fields
	Fields *string `queryParam:"style=form,explode=true,name=fields"`
	// npa policy id
	ID int `pathParam:"style=simple,explode=false,name=id"`
}

type GetNpaRulesID200ApplicationJSONStatus string

const (
	GetNpaRulesID200ApplicationJSONStatusSuccess GetNpaRulesID200ApplicationJSONStatus = "success"
	GetNpaRulesID200ApplicationJSONStatusError   GetNpaRulesID200ApplicationJSONStatus = "error"
)

func (e GetNpaRulesID200ApplicationJSONStatus) ToPointer() *GetNpaRulesID200ApplicationJSONStatus {
	return &e
}

func (e *GetNpaRulesID200ApplicationJSONStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "success":
		fallthrough
	case "error":
		*e = GetNpaRulesID200ApplicationJSONStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetNpaRulesID200ApplicationJSONStatus: %v", v)
	}
}

// GetNpaRulesID200ApplicationJSON - successful operation
type GetNpaRulesID200ApplicationJSON struct {
	Data   *shared.NpaPolicyResponseItem          `json:"data,omitempty"`
	Status *GetNpaRulesID200ApplicationJSONStatus `json:"status,omitempty"`
}

type GetNpaRulesIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// successful operation
	GetNpaRulesID200ApplicationJSONObject *GetNpaRulesID200ApplicationJSON
	// Invalid request
	NpaPolicyResponse400 *shared.NpaPolicyResponse400
}
