// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Platform/internal/sdk/pkg/models/shared"
	"encoding/json"
	"fmt"
	"net/http"
)

// Silent - flag to skip output except status code
type Silent string

const (
	SilentOne  Silent = "1"
	SilentZero Silent = "0"
)

func (e Silent) ToPointer() *Silent {
	return &e
}

func (e *Silent) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "1":
		fallthrough
	case "0":
		*e = Silent(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Silent: %v", v)
	}
}

type PatchNpaRulesIDRequest struct {
	// policy rule id
	ID               int                     `pathParam:"style=simple,explode=false,name=id"`
	NpaPolicyRequest shared.NpaPolicyRequest `request:"mediaType=application/json"`
	// flag to skip output except status code
	Silent *Silent `queryParam:"style=form,explode=true,name=silent"`
}

func (o *PatchNpaRulesIDRequest) GetID() int {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *PatchNpaRulesIDRequest) GetNpaPolicyRequest() shared.NpaPolicyRequest {
	if o == nil {
		return shared.NpaPolicyRequest{}
	}
	return o.NpaPolicyRequest
}

func (o *PatchNpaRulesIDRequest) GetSilent() *Silent {
	if o == nil {
		return nil
	}
	return o.Silent
}

type PatchNpaRulesIDStatus string

const (
	PatchNpaRulesIDStatusSuccess PatchNpaRulesIDStatus = "success"
	PatchNpaRulesIDStatusError   PatchNpaRulesIDStatus = "error"
)

func (e PatchNpaRulesIDStatus) ToPointer() *PatchNpaRulesIDStatus {
	return &e
}

func (e *PatchNpaRulesIDStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "success":
		fallthrough
	case "error":
		*e = PatchNpaRulesIDStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PatchNpaRulesIDStatus: %v", v)
	}
}

// PatchNpaRulesIDResponseBody - successful operation
type PatchNpaRulesIDResponseBody struct {
	Data   *shared.NpaPolicyResponseItem `json:"data,omitempty"`
	Status *PatchNpaRulesIDStatus        `json:"status,omitempty"`
}

func (o *PatchNpaRulesIDResponseBody) GetData() *shared.NpaPolicyResponseItem {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *PatchNpaRulesIDResponseBody) GetStatus() *PatchNpaRulesIDStatus {
	if o == nil {
		return nil
	}
	return o.Status
}

type PatchNpaRulesIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Invalid request
	NpaPolicyResponse400 *shared.NpaPolicyResponse400
	// successful operation
	Object *PatchNpaRulesIDResponseBody
}

func (o *PatchNpaRulesIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PatchNpaRulesIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PatchNpaRulesIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *PatchNpaRulesIDResponse) GetNpaPolicyResponse400() *shared.NpaPolicyResponse400 {
	if o == nil {
		return nil
	}
	return o.NpaPolicyResponse400
}

func (o *PatchNpaRulesIDResponse) GetObject() *PatchNpaRulesIDResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
