// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PatchANpaPolicyRequestBodyRuleDataMatchCriteriaAction struct {
	ActionName *string `json:"action_name,omitempty"`
}

type PatchANpaPolicyRequestBodyRuleDataPrivateAppsWithActivitiesActivities struct {
	Activity          *string  `json:"activity,omitempty"`
	ListOfConstraints []string `json:"list_of_constraints,omitempty"`
}

type PatchANpaPolicyRequestBodyRuleDataPrivateAppsWithActivities struct {
	Activities []PatchANpaPolicyRequestBodyRuleDataPrivateAppsWithActivitiesActivities `json:"activities,omitempty"`
	AppName    *string                                                                 `json:"appName,omitempty"`
}

type PatchANpaPolicyRequestBodyRuleData struct {
	AccessMethod              *string                                                       `json:"access_method,omitempty"`
	BNegateNetLocation        *string                                                       `json:"b_negateNetLocation,omitempty"`
	BNegateSrcCountries       *string                                                       `json:"b_negateSrcCountries,omitempty"`
	Classification            *string                                                       `json:"classification,omitempty"`
	ExcludedUsers             []string                                                      `json:"excludedUsers,omitempty"`
	ExternalDlp               *string                                                       `json:"external_dlp,omitempty"`
	JSONVersion               *string                                                       `json:"json_version,omitempty"`
	MatchCriteriaAction       *PatchANpaPolicyRequestBodyRuleDataMatchCriteriaAction        `json:"match_criteria_action,omitempty"`
	NetLocationObj            []string                                                      `json:"net_location_obj,omitempty"`
	PolicyType                *string                                                       `json:"policy_type,omitempty"`
	PrivateAppIds             []string                                                      `json:"privateAppIds,omitempty"`
	PrivateAppTagIds          []string                                                      `json:"privateAppTagIds,omitempty"`
	PrivateAppTags            []string                                                      `json:"privateAppTags,omitempty"`
	PrivateApps               []string                                                      `json:"privateApps,omitempty"`
	PrivateAppsWithActivities []PatchANpaPolicyRequestBodyRuleDataPrivateAppsWithActivities `json:"privateAppsWithActivities,omitempty"`
	ShowDlpProfileActionTable *string                                                       `json:"show_dlp_profile_action_table,omitempty"`
	SrcCountries              []string                                                      `json:"srcCountries,omitempty"`
	UserType                  *string                                                       `json:"userType,omitempty"`
	Users                     []string                                                      `json:"users,omitempty"`
	Version                   *string                                                       `json:"version,omitempty"`
}

type PatchANpaPolicyRequestBodyRuleOrder struct {
	Order    *string `json:"order,omitempty"`
	Position *string `json:"position,omitempty"`
}

type PatchANpaPolicyRequestBody struct {
	Description *string                              `json:"description,omitempty"`
	GroupID     *string                              `json:"group_id,omitempty"`
	RuleData    *PatchANpaPolicyRequestBodyRuleData  `json:"rule_data,omitempty"`
	RuleName    *string                              `json:"rule_name,omitempty"`
	RuleOrder   *PatchANpaPolicyRequestBodyRuleOrder `json:"rule_order,omitempty"`
}

type PatchANpaPolicyRequest struct {
	RequestBody *PatchANpaPolicyRequestBody `request:"mediaType=application/json"`
	ID          string                      `pathParam:"style=simple,explode=false,name=id"`
	// flag to skip output except status code
	Silent *string `queryParam:"style=form,explode=true,name=silent"`
}

// PatchANpaPolicy400ApplicationJSON - Invalid request
type PatchANpaPolicy400ApplicationJSON struct {
	Result *string `json:"result,omitempty"`
	Status *string `json:"status,omitempty"`
}

type PatchANpaPolicy200ApplicationJSONDataRuleDataMatchCriteriaAction struct {
	ActionName *string `json:"action_name,omitempty"`
}

type PatchANpaPolicy200ApplicationJSONDataRuleDataPrivateAppsWithActivitiesActivities struct {
	Activity          *string  `json:"activity,omitempty"`
	ListOfConstraints []string `json:"list_of_constraints,omitempty"`
}

type PatchANpaPolicy200ApplicationJSONDataRuleDataPrivateAppsWithActivities struct {
	Activities []PatchANpaPolicy200ApplicationJSONDataRuleDataPrivateAppsWithActivitiesActivities `json:"activities,omitempty"`
	AppName    *string                                                                            `json:"appName,omitempty"`
}

type PatchANpaPolicy200ApplicationJSONDataRuleData struct {
	AccessMethod              *string                                                                  `json:"access_method,omitempty"`
	BNegateNetLocation        *string                                                                  `json:"b_negateNetLocation,omitempty"`
	BNegateSrcCountries       *string                                                                  `json:"b_negateSrcCountries,omitempty"`
	Classification            *string                                                                  `json:"classification,omitempty"`
	ExcludedUsers             []string                                                                 `json:"excludedUsers,omitempty"`
	ExternalDlp               *string                                                                  `json:"external_dlp,omitempty"`
	JSONVersion               *string                                                                  `json:"json_version,omitempty"`
	MatchCriteriaAction       *PatchANpaPolicy200ApplicationJSONDataRuleDataMatchCriteriaAction        `json:"match_criteria_action,omitempty"`
	NetLocationObj            []string                                                                 `json:"net_location_obj,omitempty"`
	PolicyType                *string                                                                  `json:"policy_type,omitempty"`
	PrivateAppIds             []string                                                                 `json:"privateAppIds,omitempty"`
	PrivateAppTagIds          []string                                                                 `json:"privateAppTagIds,omitempty"`
	PrivateAppTags            []string                                                                 `json:"privateAppTags,omitempty"`
	PrivateApps               []string                                                                 `json:"privateApps,omitempty"`
	PrivateAppsWithActivities []PatchANpaPolicy200ApplicationJSONDataRuleDataPrivateAppsWithActivities `json:"privateAppsWithActivities,omitempty"`
	ShowDlpProfileActionTable *string                                                                  `json:"show_dlp_profile_action_table,omitempty"`
	SrcCountries              []string                                                                 `json:"srcCountries,omitempty"`
	UserType                  *string                                                                  `json:"userType,omitempty"`
	Users                     []string                                                                 `json:"users,omitempty"`
	Version                   *string                                                                  `json:"version,omitempty"`
}

type PatchANpaPolicy200ApplicationJSONData struct {
	GroupID  *string                                        `json:"group_id,omitempty"`
	RuleData *PatchANpaPolicy200ApplicationJSONDataRuleData `json:"rule_data,omitempty"`
	RuleID   *string                                        `json:"rule_id,omitempty"`
	RuleName *string                                        `json:"rule_name,omitempty"`
}

// PatchANpaPolicy200ApplicationJSON - successful operation
type PatchANpaPolicy200ApplicationJSON struct {
	Data   *PatchANpaPolicy200ApplicationJSONData `json:"data,omitempty"`
	Status *string                                `json:"status,omitempty"`
}

type PatchANpaPolicyResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// successful operation
	PatchANpaPolicy200ApplicationJSONObject *PatchANpaPolicy200ApplicationJSON
	// Invalid request
	PatchANpaPolicy400ApplicationJSONObject *PatchANpaPolicy400ApplicationJSON
}
