// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Platform/internal/sdk/pkg/models/shared"
	"encoding/json"
	"fmt"
	"net/http"
)

// PostNpaRulesSilent - flag to skip output except status code
type PostNpaRulesSilent string

const (
	PostNpaRulesSilentOne  PostNpaRulesSilent = "1"
	PostNpaRulesSilentZero PostNpaRulesSilent = "0"
)

func (e PostNpaRulesSilent) ToPointer() *PostNpaRulesSilent {
	return &e
}

func (e *PostNpaRulesSilent) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "1":
		fallthrough
	case "0":
		*e = PostNpaRulesSilent(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PostNpaRulesSilent: %v", v)
	}
}

type PostNpaRulesRequest struct {
	NpaPolicyRequest shared.NpaPolicyRequest `request:"mediaType=application/json"`
	// flag to skip output except status code
	Silent *PostNpaRulesSilent `queryParam:"style=form,explode=true,name=silent"`
}

type PostNpaRulesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Invalid request
	NpaPolicyResponse400 *shared.NpaPolicyResponse400
	// successful operation
	NpaPolicyResponseItem *shared.NpaPolicyResponseItem
}
